import { Geist, Geist_Mono,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({weight:["400","600","700"],
   subsets: ["latin"],
})

export const metadata = {
  title:{
    default : "My First Nextjs",
    template : "%s | My First Nextjs"
  },
  keywords: ['Next.js', 'React', 'JavaScript', "Learning", "PlayGround"],
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundColor: "white",
          color: "black",
        }}
        className={`${poppins.className}`}
      >
        <Navbar/>
        <main className="min-h-screen ">{children}</main>
        <footer className="text-center bg-green-600">
          Awesome Next js Project
        </footer>
      </body>
    </html>
  );
}
